### ISSUE TITLE
Can't view PDF in MAUI Blazor

### ISSUE THREAD

**Issue by animike** [vikramlearning/blazorbootstrap#719] opened 2024-05-18 04:14 UTC
**Description**
When running the app in Visual Studio in Windows Machine, the GUI controls show, but the pdf area is blank. When checking developer tools with ctrl+shift+i javascript errors appear reported in the console:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
> pdfjs-4.0.379.worker.min.mjs:1 

>  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
> blazor.webview.js:1 

>  Failed to fetch dynamically imported module: https://0.0.0.0/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js
> TypeError: Failed to fetch dynamically imported module: https://0.0.0.0/_content/Blazor.Bootstrap/blazor.bootstrap.pdf.js
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at BlazorBootstrap.PdfViewerJsInterop.InitializeAsync(Object objRef, String elementId, Double scale, Double rotation, String url)
>    at BlazorBootstrap.PdfViewer.<OnInitializedAsync>b__11_0()
>    at BlazorBootstrap.BlazorBootstrapComponentBase.OnAfterRenderAsync(Boolean firstRender)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
> NotifyUnhandledException	@	blazor.webview.js:1

**How to reproduce**
1. Create MAUI Blazor project
2. Follow steps from https://docs.blazorbootstrap.com/getting-started/maui-blazor-net-8
3. Add some.pdf to wwwroot
4. Add a PdfViewer with some.pdf to Home.razor `<PdfViewer Url="some.pdf" />`
5. Run on Windows Machine from Visual Studio

**Expected behavior**
The PDF is visualized.

**Screenshots**
![blazorbootstrappdfviewer](https://github.com/vikramlearning/blazorbootstrap/assets/12399477/cbfe8a3a-5269-4eb9-a4e2-94b8face10a7)

**Versions**
 - .NET Version: .NET 8
 - BlazorBootstrap: 2.2.0

**Desktop:**
 - OS: Windows 10

**Comment by gvreddy04** [comment] 2024-05-18 07:53
@animike Thank you for trying BlazorBootstrap. We will investigate this.

**Comment by kbenchari** [comment] 2024-07-11 13:20
I've been experiencing the same error for two days, trying to fix it until the idea of checking the reported issues came to mind. Thank you for posting this issue

Normally, The problem is in this js file  __content/Blazor.Bootstrap/blazor.bootstrap.pdf.js_ and especially when importing those two lines:
```

 import * as pdfJS from './pdfjs-4.0.379.min.mjs';
import * as pdfWorker from './pdfjs-4.0.379.worker.min.mjs';
```
 I hope it will be fixed soon.

**Comment by khaoula1305** [comment] 2024-07-11 14:49
I've been experiencing the same error for two days, trying to fix it until the idea of checking the reported issues came to mind. Thank you for posting this issue

Normally, The problem is in this js file  __content/Blazor.Bootstrap/blazor.bootstrap.pdf.js_ and especially when importing those two lines:
```

 import * as pdfJS from './pdfjs-4.0.379.min.mjs';
import * as pdfWorker from './pdfjs-4.0.379.worker.min.mjs';
```
 I hope it will be fixed soon.

**Closed** 2024-07-14 16:37 UTC
Labels: bug, area-maui, area-pdf-viewer
