### ISSUE TITLE
PdfViewer example throwing null reference exception in js

### ISSUE THREAD

**Issue by mark-fay-03** [vikramlearning/blazorbootstrap#662] opened 2024-04-16 20:18 UTC
### PdfViewer example throwing null reference exception in js

I have followed the Blazor Bootstrap Getting Started guide to install Blazor Bootstrap on a .NET 8 Blazor (SSR) application. I then followed the example from the PdfViewer Component on the home.razor page for both the pdf from GitHub and the hard coded pdf byte stream.

I expected the pdf to load correctly.

Unfortunately, the PdfViewer loads then the blazor.js throws the exception below (after turning on DetailedErrors in appsettings.json) before displaying the PDF's contents.

`[2024-04-16T20:12:58.956Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---`

####Versions (please complete the following information):
 - BlazorBootstrap: 2.2.0
 - Blazor WebAssembly / Server: Server
 - .NET Version: .NET 8.0

####Sample code
Same as 
[https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8#sample-code](https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8#sample-code)
[https://docs.blazorbootstrap.com/components/pdf-viewer#base64string](https://docs.blazorbootstrap.com/components/pdf-viewer#base64string)

**Comment by mark-fay-03** [comment] 2024-04-16 20:30
This also occurs with the starter template (NET8.BlazorWebAppRenderModeServerGlobal) provided in the documentation here. 
[https://github.com/vikramlearning/blazorbootstrap-starter-templates](https://github.com/vikramlearning/blazorbootstrap-starter-templates)

**Comment by gvreddy04** [comment] 2024-04-17 09:30
@mark-fay-03 Thank you for reporting this. We will investigate.

**Comment by gvreddy04** [comment] 2024-04-19 11:36
@mark-fay-03 I am unable to reproduce the issue in the starter template.

Screenshot:

![image](https://github.com/vikramlearning/blazorbootstrap/assets/2337067/e3c29b58-ad97-4767-a884-cf416a2a2c7a)

**Comment by gvreddy04** [comment] 2024-04-19 11:38
@mark-fay-03 Could you please provide a code sample or a link to a GitHub repository that demonstrates the issue with minimal steps for replication?

**Comment by gvreddy04** [comment] 2024-11-11 16:22
@mark-fay-03 Feel free to create a new issue with a sample GitHub repository containing minimal steps to reproduce the issue. Closing for now.

**Closed by gvreddy04** 2024-11-11 16:22 UTC
Labels: needs-more-info, area-pdf-viewer
