### ISSUE TITLE
Tooltip on button problem

### ISSUE THREAD

**Issue by LucaCris** [vikramlearning/blazorbootstrap#296] opened 2023-07-20 07:32 UTC
[1.9.5] Have a button with standard tooltip:

`<Button @onclick="()=>OnEditList(context)" Size="Size.Small" TooltipTitle="Test"><Icon Name="IconName.ListOl" /></Button>
`

![Screenshot 2023-07-20 092228](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/3932c65a-fdae-4e02-b7da-e3580a3bb441)

<br/>
<br/>
When I press the button, another grid replace the current one, but the old tooltip remains stucked in page:

![Screenshot 2023-07-20 092245](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/661539fd-d76c-48c8-8822-4fbb9073ef2b)

<br/>
<br/>
Even if I completely route on another page, the tooltip is here:

![Screenshot 2023-07-20 092313](https://github.com/vikramlearning/blazorbootstrap/assets/50824617/9430f584-b206-49da-b979-a0beb4290dd3)

The only way to get rid of it is to refresh (F5) the app.

Severity: tooltips on buttons cannot be used.

**Comment by MarvinKlein1508** [comment] 2023-07-27 07:24
I have the same issue. It is also present when the `Button` is within a `Tooltip` component.


For example:
```csharp
<Tooltip Title="Neuer Standort">
	<Button Color="ButtonColor.Success" @onclick="() => {}" >
		<Icon Name="IconName.Plus" Size="IconSize.x5" />
	</Button>
</Tooltip>
```

**Comment by MarvinKlein1508** [comment] 2023-07-27 07:25
It's also present in the tooltip demos: https://demos.blazorbootstrap.com/buttons

**Comment by MarvinKlein1508** [comment] 2023-07-27 07:44
I've did some testing and disposing and updating the tooltip within the `onclick` event fixes this issue for me. Not sure if there is a more elegant solution.


Within `Button` and `Tooltip` component

```csharp
protected virtual async Task OnClickAsync()
    {
        await JS.InvokeVoidAsync("window.blazorBootstrap.tooltip.dispose", ElementRef);
        await JS.InvokeVoidAsync("window.blazorBootstrap.tooltip.update", ElementRef);
    }
```

And added the handler to the link, button and span. 
```csharp
@onclick="OnClickAsync"
```

But this is definately a bug.

**Comment by LucaCris** [comment] 2023-07-28 10:17
Thanks for the workaround, but JS interop is too much for this... 😅

Waiting for official fix (not urgent)... 👍

**Comment by gvreddy04** [comment] 2023-08-04 18:56
@LucaCris @MarvinKlein1508 I'm not able to reproduce this issue.

```cshtml
<Grid TItem="Employee1"
      Class="table table-hover table-bordered table-striped"
      DataProvider="EmployeesDataProvider"
      AllowPaging="true"
      PageSize="5"
      Responsive="true">

    <GridColumn TItem="Employee1" HeaderText="Id">
        @context.Id
    </GridColumn>
    <GridColumn TItem="Employee1" HeaderText="Employee Name">
        @context.Name
    </GridColumn>
    <GridColumn TItem="Employee1" HeaderText="Designation">
        @context.Designation
    </GridColumn>
    <GridColumn TItem="Employee1" HeaderText="DOJ">
        @context.DOJ
    </GridColumn>
    <GridColumn TItem="Employee1" HeaderText="Active">
        @context.IsActive
    </GridColumn>
    <GridColumn TItem="Employee1" HeaderText="Action">
        <Button Color="ButtonColor.Primary" TooltipTitle="Edit Employee"> Edit </Button>
    </GridColumn>

</Grid>

```

https://github.com/vikramlearning/blazorbootstrap/assets/2337067/2a4ca408-fe1d-4caf-9c5b-1b501d2b1d5b

**Comment by gvreddy04** [comment] 2023-08-04 18:57
@LucaCris Please share a sample GitHub repo with minimal repro steps.

**Comment by MarvinKlein1508** [comment] 2023-08-04 20:18
@gvreddy04 you can reporduce the issue when you exhcange the content, in this case the table, with another content.

For example when you have class which is initiliazed to null you display a table with items. When you click the button you assign the current object from this row to the object and then exchange the table with another view of the object. But you can also see in your video that the tooltip does not close itself onclick.

**Comment by MarvinKlein1508** [comment] 2023-08-04 20:19
Or a more simple use case. You have a button with a tooltip which triggers a redirection.

**Closed** 2023-08-05 12:39 UTC
Labels: bug, area-tooltip, area-button
