### ISSUE TITLE
Issue in loading the Charts

### ISSUE THREAD

**Issue by PraveeshKS** [vikramlearning/blazorbootstrap#570] opened 2024-02-18 08:06 UTC
**Describe the bug**
I have been using two razor components almost same UI with a line chart, a couple of pie charts and a stacked bar chart one for customer and one for supplier in my project. Sometimes when I log into the application and navigate to the charts there won't be anything plotted in the chart, if I reload the page a couple of times it will be loaded properly. Some time it happens for Customer Report sometimes it's for Supplier. I could not reproduce this in my local machine only occurring after I deployed this in dev ops environment. Can someone help me here?

I am getting the data for the charts into a variable in OnInitialize() and assigning the datasets to the chart on the OnAfterRender()

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.11.1
 - Blazor WebAssembly / Server: Server
 - .NET Version: .NET 7

**Comment by gvreddy04** [comment] 2024-02-18 09:54
@PraveeshKS Thank you for trying BlazorBootstrap. To help us reproduce the issue you're encountering, could you please share a sample code snippet or a link to a GitHub repository?  If you're unable to reproduce the issue yourself, please provide a sample GitHub repository containing your relevant code. We'll be happy to investigate how the charts were configured and used there. If possible, it would also be helpful if you could provide a screen recording that demonstrates the issue without revealing any personal information.

**Comment by gvreddy04** [comment] 2024-11-11 16:25
@PraveeshKS Feel free to create a new issue with a sample GitHub repository containing minimal steps to reproduce the issue. Closing for now.

**Closed by gvreddy04** 2024-11-11 16:25 UTC
Labels: area-charts, needs-more-info
